name: Deploy to EC2 with Test and Rollback

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 檢出代碼
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 安裝 SSH 私鑰
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # 3. 部署應用
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          set -e
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          mv ~/django_project ~/django_project_backup_$TIMESTAMP || true

          git clone git@github.com:allenshie/stream-forge.git ~/django_project
          cd ~/django_project

          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

          python manage.py migrate
          python manage.py collectstatic --noinput

          sudo systemctl restart gunicorn
          EOF

      # 4. 測試應用程序
      - name: Run Tests
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          set -e
          cd ~/django_project
          source venv/bin/activate

          # 運行測試
          pytest --maxfail=1 --disable-warnings -q
          EOF

      # 5. 驗證部署
      - name: Verify Deployment
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://${{ secrets.EC2_PUBLIC_IP }})
          if [ "$RESPONSE" -ne 200 ]; then
            echo "Deployment verification failed with response code: $RESPONSE"
            exit 1
          fi

      # 6. 回滾機制
      - name: Rollback if Deployment Fails
        if: failure()
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          set -e
          LATEST_BACKUP=$(ls -td ~/django_project_backup_* | head -n 1)
          if [ -d "$LATEST_BACKUP" ]; then
            rm -rf ~/django_project
            mv $LATEST_BACKUP ~/django_project

            sudo systemctl restart gunicorn
          else
            echo "No backup found for rollback!"
            exit 1
          fi
          EOF
